{% set version = '1.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-purbayes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PurBayes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PurBayes/PurBayes_{{ version }}.tar.gz
  sha256: 1097eefd636ba2a71cb9b31917d75e5841cd0ccad44fb9e4e27c399e3d237559

build:
  number: 1005
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rjags
  run:
    - r-base
    - r-rjags

test:
  commands:
    - $R -e "library('PurBayes')"           # [not win]
    - "\"%R%\" -e \"library('PurBayes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=PurBayes
  license: GPL-2.0-only
  summary: PurBayes is an MCMC-based algorithm that uses next-generation sequencing data to estimate
    tumor purity and clonality for paired tumor-normal data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
