travis:
  secure:
    BINSTAR_TOKEN: LcHxWAD//AHGaIr7sosqnNAmeR5GsX1dciW39RV68dR2eNKeB47jilOHKf8yaUaixcBPtygv0K/V0TJqBN+L+NT51aP09hABgcxVjUM2VNXcIEZsX/ytZeDNmIXlUVuTPGWpF0GukLbiawtbSJsiGxIvHjXhM5Oz/bKulJarmbZjRp/yPHvlWsNDmX+3bj7mws73PPv8C64+Aom7XPOqfe1+EGxeGC1Ae6jWgiWsB+dYGMkR/ethzD5BMVHv5yaIiXUfnt3T96+ozM+vgxryDw02fgb+1j4EtKBVyALLbxVGVIuB/641GrF65Q9evVGrjg3R/SZna3V0V5+1KUsy40Ik/7ArIxNKPaEbAgWpLdx4AwaTLtCWdr9QTtjStYH1EETgNscyL5b5aZednYOIS8cusDHHuTbZfl2KNN+62V8GU921I0UCBtxVNgZBn/nPXSv8PFUgFnKgEEUf5mC3v0JaugKwSg8AFKaVRL1YUfcDck8h4dBZlWW4AdIcBNoWzjuzZRmK43YTS5IrRRh4jQKCC8MmQOAJrIV1augzZ82EoRptBTysOVywd/xiTTlj/Qs95RpT4exNVVntaexOhtMH34ocHPYn7jveJFELPrSNKTKoqHxiI7dZaoIvUWSPjghR+i6fP0r1RhbAuNVlmj74woFKMANxpcvFWYc/FyA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
