travis:
  secure:
    BINSTAR_TOKEN: CNckYlJXkp9lExwMilsjYyNoe1Gx62wuPUAuTw5o6NN1+fWDpg1Cn6Qt2f2tXrLGneQGivt6GHUN8WFh9Wl+Ho1qEkvtRDXNs/PsBwAjCjJf6eo7vtgoLrFuV5AtchfmdUzh54wMnTwtrbHUcolmYwNOc+3VQ6xQ7ecQnaIlsnsbp6B6BpYTDXUtwYnviKIQb8IzoQ1+em6i1WBD/w1ZNA95LIKn8j2d5AWjY0cmK2twrKUp2IHgVjdFFhBhBloMPrKVpmpLsX2qmxvnCi0AtsQv1FL4zvIu8gGxU9JUmYLXQpwhVYH2iOFqzjErETXtniu1brVaHVst3lXG9vdQoDAG9kRhhn2j/mOigQvwE6ZmhFXM1teUh1e1WBtr52RcsHRtzqEOqNbbMDmYS1WX1mj2U5zfoI5IAvVpvYMUJxCg31fiJk26ZoOIf0Q0H2UXsmFvzPgwqTouXjVUWgzgokuvb4sQcU3dcs9GAL5uLy3YSYyxjHDSq0aGJjiBcUQHutm8MNk/2cBiROYjMRE8bh/OJ8L8tqB0bYZWF+hR/7N5N3BFQOarzMOKyVYA/fJqtdi24mIagLgEa3Gqbe8nbb7lpi8izg42N8HeW5Ik7jM89b0+WDaahyFvnHkz7Gn0zJpYQLlqewkFtEafelHSaTQ6mSDIvXAwIQu5xbAJyjw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
