appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sVIbfSMJ06nfRNnvcsI9z7ipkuBaDuPT0KVVCYa8IVk7VQvh+SrDSQ5WwTWwdRAHLFjtTLrhCq2Ls+7jlLIiTfJr6cNMJCuCHiHvodfpu8+I3+aLlH2NPLkrbW0CLebwJ4+Q55P9eCqvHoaMmpZU1g1lg6G+++j24iiU+YC9hDWhWjjpov8lKeaYelUR1QwD6yQtkCcZ1WxluBdMpC+D6PbCuqRGYemTUX2yhyA66ZUR7Rfd5gwqlr0bR/wn7UZ7Q/0rejAvt/qIv6SZzY8tkMOjua4s02TLGMw1aAPWuIcfN3ELET3XUK5D1IzN4XkPLcyhUwC6memLKiMP29vkRTlJaP+KP3+ciRHS9yfjTO7/kCPFoM2XxyqpdhLGHMukt7lPAVNs09JjOJVbo+ZK+U2sWJ9ELA+aOT6PvC28dU8ib67+qgKQBr4SIAD/sSoC23a9vf/AQMQnTK2PxeIwi8ntRdcu+lwkNxqKWxGrCKU7iIWNPTKUDCM8Z8v9GbXgrVz/IFZMRdV/vJJKeQLeDEeVxy42gzjUDvWj34JnP1bHeemUQ/aLVy3OdyTaLldqb3iYCgw29r3PfljPxlkz2fwx4CmhgQbKFp3VQluBE+FFC9h6zjNtpCxmgvLEcyBiNDhvNIHLu2PIg8xl92dgMPR5dYQ9g3WMISBYCzVG9Oo=}
