travis:
  secure:
    BINSTAR_TOKEN: XqQFg/1+jaTh/EQxZxXTj8MeZP/d/0hgWzKaz4SdqL2elP4fhr0pkbDojsjdQyYE2TYVEy4Y4GNwS1+FDBzGYWeLWhJYRRVDzYI2xTDtbyubzep5n0CEcGbE2KxUmJBA2VntjduX/n0pDj+BwEwULrEWyKjbS2Sk2zbCdYFuQ9uBRnrwglsTSBvUqgQngCk2eyzcFOJRaGB5L0dae1+9WgPS33Zq/Z8reWNYqYCRyvay1LYfE8AbTg1iI5NDK+QFFzWZK53FmwzL3FID5Oue72SY//dDDEzpsOOrL4Qho3ZXbHOfIANF+4Wst9BTUfALbfKZ7kPmhNGFMbdnj6NjX1Sl7dKVMkV0b6WUa/thGUBFSDJUMmHCEeCOKKAc12BYFZXGWhZU7+iP/8FMX51Sdnw7prf18TEPXt6UBZ/F+wY/huJ599Yn97eeJjcfStDF2cKtVlLaVlbB/Ko1eZkrtuOXd91FUwkg/wOrjYKv75RmLxSktWdgs+PtvgGvLCbqQtpaEtLNgOO9pKG8gJfqslpo6mAfmsXCxJHHvLUvwmcxBTq1iuNjP1KZ78vsdyuCWQlr37o5qJOaz+n43MkmfxzOa8u3freKti4qkr/xcp3Xi3vnEEkQfZ5nRRNozL/qUaQwyX3FGhVM9wKxiF8xthdNKaVw4AFansueZkfhMCU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
