travis:
  secure:
    BINSTAR_TOKEN: ndPOIRdzNlJHX0ll8HAkeGDoGBcRHFfzOi01XPQoR7vOZcNhdZDxfjeQ2+OELQWG0xTfceOrYhDcaATIdKtNKwoNjWZuKnCf27k+A2ukESguTd0OVFbpwG+2tbCSQdrX5jXceC28bPzj+tdbc8HtJgAirHVmRGtcqeMe5O9sLBtgMb9g917YHbYK1LCa3fGtK+GBVvbMgzQnECsg55Y2K7pwCpu7dsG2Pve2JGC+nowg9CVv5J58RrWFsuCovq5fN8I+ENusLRfhO+zvIoMrzwmzZwQfKJYfl9BRzdRbpEA6nHVFgFPdTajSQYG1tHNVzkXy3RmX7oTFfHal4xDDu+3BMx/RtgrMCkFyY/C+5gr/8TKux8QcwxaADlKW7BgHHKSUPAwVqAC5S8dig6JvzmCrzRN0QptnmNzic7HRl3R9EhNerjgD5JH+ctK/J/pCxCIRMHyiTDKhy4gpPc9nIjTFEw0mhpHV/G5TZE5VT463zPdo0ra3Uq39Il2WD805ePcz/ufGx/LlLsLeBHDUuTu2Lu4pUtBz2V3wJu9qohCGxwR0R2vcD8Ztfl1qnNSvRyJKSxbgYykczMRgz1Onhs3bBOjJLQAMu1tb12XONs1RJBTtcxYRkF/gCFmQStK00DWnTq+d0oHYn+zKpuQi4VqChCJqLahCCDowoHOOpEw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
